version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./src:/usr/src/server/src"
    depends_on:
      - db
    ports:
      - "9001:9001"
    stdin_open: true
    tty: true
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
